### ISSUE TITLE
Scrolling to titles on information pages

### ISSUE THREAD

**Issue by Paula-Kli** [fsr-de/myHPI#417] opened 2023-10-25 15:11 UTC
Information pages have a cool short menu on the right to quickly go to titles of interest. When clicking on those the page scrolls to them which is cool. Unfortunately it scrolls a bit to far up and the title gets hidden under the Menu bar at the top (at least if it has two lines of entries)

**Comment by frcroth** [comment] 2023-10-29 12:50
Duplicate of #329

**Closed by frcroth** 2023-10-29 12:50 UTC
Labels: [T] bug
